name: "MUP Deploy"
description: "Deploy a Meteor application using Meteor Up"
inputs:
    environment:
        description: 'The environment to deploy the app to. Either "STAGING" or "PRODUCTION".'
        required: true
runs:
    using: "composite"
    steps:
        - run: ls ${{github.action_path}}
          shell: bash
        - run: .${{github.action_path}}/install.sh
          shell: bash
