name: "MUP Deploy"
description: "Deploy a Meteor application using Meteor Up"
inputs:
    mode:
        description: 'The MUP script to run. Either "DEPLOY", "SETUP", or "RESTART"'
        required: true
    meteor_deploy_path:
        description: "The relative path to Meteor's .deploy directory"
        required: true
    package_manager:
        description: 'The node package manager to use. Either "NPM", "PNPM", or "YARN"'
        required: true
    project_path:
        description: "The path to the folder that contains the package.json for the Meteor app. Defaults to the current directory"
        required: false
        default: "."
    run_setup_on_deploy:
        description: "Should mup setup be run on every mup deploy"
        required: false
        default: "false"
    mup_version:
        description: "The version of mup to install. Defaults to latest"
        required: false
        default: "latest"
runs:
    using: "composite"
    steps:
        - run: chmod +x ${{github.action_path}}/script.sh && sh ${{github.action_path}}/script.sh ${{ inputs.mode }} ${{ inputs.meteor_deploy_path }} ${{ inputs.package_manager }} ${{ github.workspace }} ${{ inputs.project_path }} ${{ inputs.run_setup_on_deploy }} ${{ inputs.mup_version }}
          shell: bash
